[package]
name = "weather_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.14", features = ["blocking", "json"]}
serde = {version="1.0.219", features = ["derive"]}
clap = {version = "4.5.32", features = ["derive"]}
colored = "2.2.0"